name: Main CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-image-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Frontend Image
        run: |
          cd frontend
          docker build -t nickpominov/lm-frontend:latest .
          docker push nickpominov/lm-frontend:latest

      - name: Build and Push Backend Image
        run: |
          cd backend
          docker build -t nickpominov/lm-backend:latest .
          docker push nickpominov/lm-backend:latest

      - name: Deploy to remote server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd /srv/lenka-messenger
            docker-compose -f docker-compose.prod.yaml up -d --no-deps lm-backend lm-frontend